#!/bin/sh
show_menu(){
    normal=`echo "\033[m"`
    menu=`echo "\033[36m"` #Blue
    number=`echo "\033[33m"` #yellow
    bgred=`echo "\033[41m"`
    fgred=`echo "\033[31m"`
    printf "\n${menu}*********************************************${normal}\n"
    printf "${menu}**${number} 1)${menu} Festplatte /dev/sda1 mounten ${normal}\n"
    printf "${menu}**${number} 2)${menu} Festplatte /dev/sda2 mounten ${normal}\n"
    printf "${menu}**${number} 3)${menu} Festplatte /dev/sda3 mounten ${normal}\n"
    printf "${menu}**${number} 4)${menu} Festplatte /dev/sdb1 mounten ${normal}\n"
    printf "${menu}**${number} 5)${menu} Festplatte /dev/sdb2 mounten ${normal}\n"
    printf "${menu}*********************************************${normal}\n"
    printf "Bitte gebe eine Zahl ein oder Tippe ${fgred}x zum verlassen. ${normal}"
    read opt
}

option_picked(){
    msgcolor=`echo "\033[01;31m"` # bold red
    normal=`echo "\033[00;00m"` # normal white
    message=${@:-"${normal}Error: No message passed"}
    printf "${msgcolor}${message}${normal}\n"
}

clear
show_menu
while [ $opt != '' ]
    do
    if [ $opt = '' ]; then
      exit;
    else
      case $opt in
        1) clear;
            option_picked "Option 1 ausgewählt. /dev/sda1 wird versucht zu mounten";
            sudo mount -t ntfs-3g -o utf8,uid=pi,gid=pi,noatime /dev/sda1 /media/Kara;
            show_menu;
        ;;
        2) clear;
            option_picked "Option 2 ausgewählt. /dev/sda2 wird versucht zu mounten";
            sudo mount -t ntfs-3g -o utf8,uid=pi,gid=pi,noatime /dev/sda2 /media/Kara;
            show_menu;
        ;;
        3) clear;
            option_picked "Option 3 ausgewählt. /dev/sda3 wird versucht zu mounten";
            sudo mount -t ntfs-3g -o utf8,uid=pi,gid=pi,noatime /dev/sda3 /media/Kara;
            show_menu;
        ;;
        4) clear;
            option_picked "Option 4 ausgewählt. /dev/sdb1 wird versucht zu mounten";
            sudo mount -t ntfs-3g -o utf8,uid=pi,gid=pi,noatime /dev/sdb1 /media/Kara;
            show_menu;
        ;;        
        5) clear;
            option_picked "Option 5 ausgewählt. /dev/sdb2 wird versucht zu mounten";
            sudo mount -t ntfs-3g -o utf8,uid=pi,gid=pi,noatime /dev/sdb2 /media/Kara;
            show_menu;
        ;;
        x)exit;
        ;;
        \n)exit;
        ;;
        *)clear;
            option_picked "Bitte gebe eine Zahl ein oder Tippe x zum verlassen";
            show_menu;
        ;;
      esac
    fi
done
